apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-example-com-cert
  namespace: cert-manager
spec:
  secretName: k8s-example-com-cert-secret
  duration: 43800h # 5y
#  duration: 8760h # 1y
  isCA: true
  commonName: '*.k8s-example.com'
  dnsNames:
    - k8s-example.com
    - '*.k8s-example.com'
  issuerRef:
    name: k8s-example-ca-issuer
    kind: ClusterIssuer